In [1]:
# PyTorch Install
# pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html

# Torch vision
# pip install torchvision

#  !pip install into Jupyter

# pip install opencv-python 
# pip install tqdm

# Jupyter notebook themes
# pip install jupyterthemes

##original theme
# jt -r

#reset theme with tool bar
# Toolbar Visible -T
# Name & Logo Visible -N
# Kernel Logo Visible -kl
# their defaults are set to none

#change the theme need to reset JN at first but then you just have to refresh 
# !jt -t gruvboxd -T -N -kl

## black theme
#jt -t chesterish
##List of Themes
# !jt -l

# onedork
# grade3
# oceans16
# chesterish
# monokai
# solarizedl
# solarizedd

In [2]:
# sentdex building our neural network on youtube

In [3]:
import torch
import numpy as np
import pandas as pd
import torchvision
from torchvision import transforms, datasets
import torch.utils.data
import matplotlib.pyplot as plt
import torch.optim as optim

In [4]:
#Build model 
# obj oriented programming
import torch.nn as nn
#functions
import torch.nn.functional as F

import os
import cv2
import numpy as np
from tqdm import tqdm

import torch.nn as nn
import torch.nn.functional as F

In [5]:

X=torch.Tensor([5,3])        #tensor is array
y=torch.Tensor([2,1])

In [6]:
print(X*y)

tensor([10.,  3.])


In [7]:
X=torch.zeros([2,5])
print(X)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
X.shape

torch.Size([2, 5])

#### Random variables in array

In [9]:
y=torch.rand([2,5])
print(y)

tensor([[0.7216, 0.3050, 0.2310, 0.2371, 0.7292],
        [0.5941, 0.8966, 0.2333, 0.4403, 0.2146]])


In [10]:
# reshape something--view method
#flatten operations 2,5 cannot go into nn inot 1 by 10
# need to reassign
y=y.view([1,10])
print(y)


tensor([[0.7216, 0.3050, 0.2310, 0.2371, 0.7292, 0.5941, 0.8966, 0.2333, 0.4403,
         0.2146]])


# Data

In [11]:
# vision is cheating with built in data

In [12]:
# locally use "", transforms.Compose([all transforms apply to data])
#have to convert to tensor--transforms.ToTensor()

# This gets data downloaded into variables 
train = datasets.MNIST("", train=True, download=True,
                      transform=transforms.Compose([transforms.ToTensor()]))

test =datasets.MNIST("", train=False, download=True,
                      transform=transforms.Compose([transforms.ToTensor()]))

In [13]:
#load obj
# batch size-how many at a time pass to model
# shuffle-
#mnist-hand drawn digits from 0 to 9, 28 by 28 image

trainset=torch.utils.data.DataLoader(train, batch_size=10, shuffle=True)
testset=torch.utils.data.DataLoader(test, batch_size=10, shuffle=True)

In [14]:
# iterate
for data in trainset:
    print(data)
    break

[tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0

In [15]:
#last temp variable in a for loop can still be accessed
# data is a tensor object with x and y , second x,y tensors with labels
X,y = data[0][0], data[1][0]
print(y)

tensor(2)


In [16]:
print(data[0][0].shape)
# not a typical image on grayscale converted into tensor 
#(that would be 28 by 28 but pytorch wants that 1 there)


torch.Size([1, 28, 28])


In [17]:
# # view is like reshape but not inplace
# plt.imshow(data[0][0].view(28,28))
# plt.show

In [18]:
# balancing-model finds shorter path, optimizer decreases loss as easy as possible
# data sets include data from 0 to 9 but if 60% data set is 3s this will be the easiest way to preditc
total =0
counter_dict = {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0}

for data in trainset:
    # xs and ys stored in variables
    Xs,ys =data
    for y in ys:
        # convert into dictionary key
        # how many samples for each number
        counter_dict[int(y)] +=1
        total +=1
print(counter_dict)
    

{0: 5923, 1: 6742, 2: 5958, 3: 6131, 4: 5842, 5: 5421, 6: 5918, 7: 6265, 8: 5851, 9: 5949}


In [19]:
# gives the percentage distribution
for i in counter_dict:
    print(f"{i}: {counter_dict[i]/total*100}")

0: 9.871666666666666
1: 11.236666666666666
2: 9.93
3: 10.218333333333334
4: 9.736666666666666
5: 9.035
6: 9.863333333333333
7: 10.441666666666666
8: 9.751666666666667
9: 9.915000000000001


# Building Neural Network

In [20]:
class Net(nn.Module):
    def __init__(self):      # initialization method is not run
        super().__init__()   # super correspons to nn.Module to initialize
        # want initalization to run with parent class inheriting from
        # define fully connected layers to nn
        self.fc1 = nn.Linear(28*28, 64)   #fc1 is fully connected 1st layer, input and output to each layer, input is rows of image pizels flatten
        self.fc2 = nn.Linear(64, 64)   #nn.linear is fully connected flattened
        self.fc3 = nn.Linear(64, 64)   # 784 is 28*28, output is 3 layers of 64 layers so out put is 64, each layer has input coming into layer (flattened image) output is 64
        self.fc4 = nn.Linear(64, 10)   # go from image to code, 64 is extent to hidden layer
        # fc2 takes in 64, fc3 takes in 64 but can output anythin
        # 10 classes ( 10 neurons)
        # without super error-cannot assign module before Module.__iinit__() call
    
    # dont have path for data to take for layer feed forward layer from one side ot the other side
    #feed forward
    def forward(self, X):
        X= F.relu(self.fc1(X))      # X is going to pass through the layers
        X= F.relu(self.fc2(X))      # relu activation layer using F.relu-whether the neuron is firing-keeps outputs from giving crazy numbers
        #activation funciton is to make it a nonlinear function
        X= F.relu(self.fc3(X))
        X= self.fc4(X)   #just pass the data, activaiton on 64 only , dont want relu , want one neuron fully fired [0,0,1] (dog, cat, human)
        
        return F.log_softmax(X, dim=1) #dimenison apply softmax for multiclass = dim=1 similar to axis probablity distribution goes to 1--- what do we want to sum to 1? care about classes themselves-distributing across the batches to 1---batch of tensors to sum to 1

net =Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=10, bias=True)
)


In [21]:
#has to be flattened first
# -1 specifies unkonwn shape
X = torch.rand((28,28))
X=X.view(-1,28*28)
# output=net(X)

In [22]:
# actual predictions
# grad_fn---passes data through
output=net(X)
output

tensor([[-2.4401, -2.2816, -2.2858, -2.3508, -2.2744, -2.2471, -2.3368, -2.3303,
         -2.2261, -2.2697]], grad_fn=<LogSoftmaxBackward>)

# Training Model

In [23]:

# net.parm is everything is adjustable in model, later latyers are specific to tasks
#transfer learning
    # first few layers small general
    # later layers specific
# transfer learning-freeze first few layers only let model adjust weights on last layers

#learning rate-optimization curve-converge to the bottom of the curve
    # size of step to lower the loss with certain szie steps

In [24]:
optimizer=optim.Adam(net.parameters(), lr=0.001 ) # 1e-1
#decaying learning rate-larege initial steps but smaller and smaller to converge at bottom
#iterate over data and pass through model
#epoch is full pass through data
EPOCHS=3
for epoch in range(EPOCHS):
    for data in trainset:
        #data is a batch of feture sets and labels
        X, y = data #unpack
        #There are rows of pixels that we need to flatten
#         print(X[0])
#         print(y[0])
#         break
        #everytime calculate loss, optimize model, make gradients
        #everytime pass data through nn
        # zero the gradient to prevent batches added together
        #only pass through one set of labels but still get benefit of batch training
        # gradients contain loss-optimizer uses gradients for weights
        net.zero_grad()
        #batch data decreases training time,dont want to pass entire dataset
        #bt batch size of 32 and 128 helps to generalize-weak GPU only pass through one set of labels
        output=net(X.view(-1, 28*28))
        #caluclate how wrong
        #loss calculation-numerical-one hot vectors= output-array is one is on, zero is off[0,1,1]-mean squared error, regission something else
        #loss calculation-scaler-singular value-different loss metric-not a vector-nll_loss
        loss=F.nll_loss(output, y)
        #which loss is applicable to each environment and what is loss doing
        #back propogate the loss
        # 
        loss.backward()
        #adjust weights for us
        optimizer.step()
    # expect loss to be close to zero
    print(loss)
        

tensor(0.4851, grad_fn=<NllLossBackward>)
tensor(0.0109, grad_fn=<NllLossBackward>)
tensor(0.0352, grad_fn=<NllLossBackward>)


In [25]:
correct=0
total=0
#validate data, dont need gradients
#how right or wrong the model is

with torch.no_grad():
    #net.train and net.eval()-dictabte training or eval model before--old
    for data in trainset:
        X,y=data
        output=net(X.view(-1,784))
        #want to compare argmax
        for idx, i in enumerate(output):
            if torch.argmax(i) ==y[idx]:
                correct +=1
            total+=1
# for every prediciton does it match target value
print("Accuracy: ", round(correct/total, 3))

Accuracy:  0.978


In [26]:
# import matplotlib.pyplot as plot
# plot.imshow(X[0].view(28,28))
# plt.show()

In [27]:
print(torch.argmax(net(X[0].view(-1,784))[0]))

tensor(2)


# Grab Premade data set of raw inmages to build new model

In [28]:
# convolutional nn-new type of layer
#use them for image tasks-but convolutional nn outpreform recural nn
#this is 1D convolutional nn

#convolutional nn
#pass the image in its form so dont have ot flatten image
#accepts 2D input and even 3D input-so could put in 3D printing models
#its pixels-2D-apply convolution to locate features of image
#breaks into window(kernal)-looks for feature in 3x3 pixels
## nn works on numbers and not strings-but convolutional nn-first layer finds things like edges, curves, corners
#then passes through another layer to find more ocmplex features like circles, etc..
#finds features then slides over the entire image and condenses the image
# find 30 features of image

#after convolution get a new condensed version with numbers of the features
#pool using a window(max pooling is the most common)-takes the max value, then slides and does it again

#really simplifying image looking for features-have 2, 3, 4 convolutional layers
#first layer-just basic features-edges, cormers,curves-combination of pixels
#next layer is combination-sees combination of curves, edge, and curves to find circles, sqares, etc
# next layer is finding even more combinations


In [29]:
REBUILD_DATA=True # set to true once then back to false unless you want 
class DogsVSCats():
    IMG_SIZE=50 # make images 50 by 50, images are different sizes and shapes
    #want them all to be normalized set the smallest dimentions to 50
    # go and resize, pad, rotate, flip, 
    CATS="PetImages/Cat"
    DOGS="PetImages/Dog"
    LABELS={CATS:0, DOGS:1}
    training_data=[]
    catcount=0
    dogcount=0
    
    def make_training_data(self):
        # iterate over cats and dogs-keys of dictionary
        for label in self.LABELS:
            print(label)
            #iterate over all the images in the directories
            for f in tqdm(os.listdir(label)): #tqdm-progress bar where we are(directory)
            #f is the file name but want the path
                try:
                    path=os.path.join(label,f)
                    img=cv2.imread(path, cv2.IMREAD_GRAYSCALE) #converitng to grayscale, not necessary butdense layers,nn will need to be flat 
                    # convolutionlal layer will not need to be flat
                    # color adds channels but not dimensions but its added data that we dont need- is this relevant
                    img=cv2.resize(img,(self.IMG_SIZE, self.IMG_SIZE))
                    self.training_data.append([np.array(img), np.eye(2)[self.LABELS[label]]]) # convert scaler values to one hot vector (0 or 1) but in an index- use np.eye(5) to make 5x5 with 1s
                    if label ==self.CATS:
                        self.catcount +=1
                    elif label ==self.DOGS:
                        self.dogcount+=1
                except Exception as e:
                    pass
                    #print(str(e)) # to identify errors
        np.random.shuffle(self.training_data)
        np.save("training_data.npy", self.training_data)
        print("Cats: ", self.catcount)
        print("Dogs: ", self.dogcount)

if REBUILD_DATA:
    dogsvcats=DogsVSCats()
    dogsvcats.make_training_data()
                

PetImages/Cat


  0%|                                                                                | 4/12501 [00:00<06:51, 30.37it/s]

PetImages/Dog


100%|███████████████████████████████████████████████████████████████████████████| 12501/12501 [01:26<00:00, 145.28it/s]


Cats:  12476
Dogs:  12470


In [30]:
# np.eye(10)[7]

In [31]:
training_data=np.load("training_data.npy", allow_pickle=True)

In [32]:
print(len(training_data))

24946


In [33]:
print(training_data[0])

[array([[ 75,  82,  78, ..., 226, 213, 225],
       [ 80,  78,  92, ..., 185, 190, 237],
       [ 90,  95,  93, ..., 203, 199, 203],
       ...,
       [103, 115, 118, ..., 103,  94, 101],
       [111, 112, 124, ..., 104,  99,  96],
       [100, 119, 123, ..., 100,  99,  99]], dtype=uint8)
 array([0., 1.])]


In [34]:
# import matplotlib.pyplot as plt
# plt.imshow(training_data[1][0], cmap="gray")
# plt.show()

In [35]:
training_data[1][1]

array([0., 1.])

In [36]:
# build the model itself

In [43]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 32, 5) #input, 32 convolutional features, kernal size (5x5 window to roll over the data to find features)
        self.conv2 = nn.Conv2d(32, 64, 5) #2d layers (x and y axis)
        self.conv3 = nn.Conv2d(64, 128, 5) 
        #has to output into a linear layer as a distrbution of predictions
        #tensorFlow-keras has a flatten function
        x = torch.randn(50,50).view(-1,1,50,50) # how ever images will be in tensor form input image: 1x50x50
        self._to_linear = None
        self.convs(x) 
        #need to run data into con1, con2, con3 then check the shape and multiple dimensions.
        #comment out self.fc1 and 2 then pass random data andn pass through self.convs(x)
        #have to know self._to_linear with quick forward pass
        self.fc1 = nn.Linear(self._to_linear, 512) #flattening.
        self.fc2 = nn.Linear(512, 2) # 512 in, 2 out bc we're doing 2 classes (dog vs cat).
        
        
    def convs(self, x):
        # max pooling over 2x2
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2)) # 2,2 is the shape of the pooling
        x = F.max_pool2d(F.relu(self.conv2(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv3(x)), (2, 2))
#         print(x[0].shape)
        if self._to_linear is None:
            self._to_linear = x[0].shape[0]*x[0].shape[1]*x[0].shape[2]
         #X is coming in as a batch of data
        # return x to create forward 
        return x
#         self.fc1=nn.Linear(self._to_linear, 512) #have to find the input
#         self.fc2=nn.Linear(512, 2) #2 classes
    
    def forward(self, x):
        x = self.convs(x)
        x = x.view(-1, self._to_linear) #reshape to be flattened, we need to know the number before we call it in the initailiation
        # have to know this flattened number
        x = F.relu(self.fc1(x)) #first fully connected layer
        x = self.fc2(x)
        return F.softmax(x, dim=1)# dont need activation layer bc just a bunch of vectors being multiplied together
        # dim=1 because of the batches, x is a batch of Xs, 0th dimension wouldd be all dimesntions, want distribuition (0 to 1 percentatge) distributed across cat and dog classifications
        # this one can fit, train on x and it would work
    
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 32, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1))
  (conv3): Conv2d(64, 128, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=512, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=2, bias=True)
)


In [44]:
#  torch.flatten(input, start_dim=0, end_dim=-1) # Pytorch has its own flatten method

# Have training data

In [49]:
optimizer = optim.Adam(net.parameters(), lr=0.001)
#mean squared error for 0 and 1
loss_function = nn.MSELoss()
#seperate out Xs and ys-make them a tensor- i[0] just the Xs
X = torch.Tensor([i[0] for i in training_data]).view(-1,50,50)
# scaling imadry, pixel bt 0 and 255 and want them to be between 0 and 1
X = X/255.0
y = torch.Tensor([i[1] for i in training_data]) 

In [50]:
# split train and test data by simply slicing out val size
VAL_PCT = 0.1 #tests against 10% of data set
val_size = int(len(X)*VAL_PCT)
print(val_size) # validation tests size int slice
train_X = X[:-val_size]
train_y = y[:-val_size]

test_X = X[-val_size:]
test_y = y[-val_size:]

2494


In [51]:
# determine batch size, memory error-lower batch size
BATCH_SIZE = 100
EPOCHS = 1

# Slices through training data, first batch is 0 to 100 index through training dataset 
for epoch in range(EPOCHS):
    #take steps that are the size of BATCH_SIZE
    for i in tqdm(range(0, len(train_X), BATCH_SIZE)):
        #tqdm is progress bar
#         print(i, i+BATCH_SIZE) 
        batch_X = train_X[i:i+BATCH_SIZE].view(-1, 1, 50, 50) #reshape with view
        batch_y = train_y[i:i+BATCH_SIZE]
        
        #zero gradients
        net.zero_grad()
        #model.zero_grad
#         optimizer.zero_grad #above-optim.Adam-net parameters-no diff bt net.zer or optimizer.zer---might have model that might have diff optimizers on diff sizdez, muliltiple potimzers
        #want to use the specific optimizer (adam, etc) whic hway do you need to be explitc, just this optimzizer, just need to know which is which
        outputs = net(batch_X) #gives outputs to calculate loss-use loss function above
        loss = loss_function(outputs, batch_y)
        loss.backward()
        optimizer.step()
    print(f"Epoch: {epoch}. Loss: {loss}")

100%|████████████████████████████████████████████████████████████████████████████████| 225/225 [01:56<00:00,  1.93it/s]

Epoch: 0. Loss: 0.22874847054481506


In [52]:
correct = 0
total = 0
with torch.no_grad():
    for i in tqdm(range(len(test_X))):
        real_class = torch.argmax(test_y[i])
        net_out = net(test_X[i].view(-1, 1, 50, 50))[0]  # returns a list, 
        predicted_class = torch.argmax(net_out)

        if predicted_class == real_class:
            correct += 1
        total += 1
print("Accuracy: ", round(correct/total, 3)) 

100%|█████████████████████████████████████████████████████████████████████████████| 2494/2494 [00:12<00:00, 193.44it/s]

Accuracy:  0.649
